package org.schabi.newpipe.extractor.stream;

import com.github.catvod.spider.merge.b.b;
import com.github.catvod.spider.merge.n1.d;
import com.github.catvod.spider.merge.s0.a;
import java.util.Locale;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.exceptions.ParsingException;
import org.schabi.newpipe.extractor.services.youtube.ItagItem;
import org.schabi.newpipe.extractor.utils.LocaleCompat;

/* compiled from: r8-map-id-88b4ee5a47df08811008f50aae82e56df8b70dc6cf3967c4f5ff89d9e4610885 */
/* loaded from: classes.dex */
public final class SubtitlesStream extends Stream {
    private final boolean autoGenerated;
    private final String code;
    private final MediaFormat format;
    private final Locale locale;

    /* compiled from: r8-map-id-88b4ee5a47df08811008f50aae82e56df8b70dc6cf3967c4f5ff89d9e4610885 */
    public final class Builder {
        private Boolean autoGenerated;
        private String content;
        private DeliveryMethod deliveryMethod = DeliveryMethod.PROGRESSIVE_HTTP;
        private String id;
        private boolean isUrl;
        private String languageCode;
        private String manifestUrl;
        private MediaFormat mediaFormat;

        public SubtitlesStream build() {
            if (this.content == null) {
                a.h("No valid content was specified. Please specify a valid one with setContent.");
                return null;
            }
            if (this.deliveryMethod == null) {
                a.h("The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod.");
                return null;
            }
            String str = this.languageCode;
            if (str == null) {
                a.h("The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode.");
                return null;
            }
            if (this.autoGenerated == null) {
                a.h("The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated.");
                return null;
            }
            if (this.id == null) {
                MediaFormat mediaFormat = this.mediaFormat;
                this.id = str.concat(mediaFormat != null ? b.n(".", mediaFormat.suffix) : VideoStream.RESOLUTION_UNKNOWN);
            }
            return new SubtitlesStream(this.id, this.content, this.isUrl, this.mediaFormat, this.deliveryMethod, this.languageCode, this.autoGenerated.booleanValue(), this.manifestUrl, 0);
        }

        public Builder setAutoGenerated(boolean z) {
            this.autoGenerated = Boolean.valueOf(z);
            return this;
        }

        public Builder setContent(String str, boolean z) {
            this.content = str;
            this.isUrl = z;
            return this;
        }

        public Builder setDeliveryMethod(DeliveryMethod deliveryMethod) {
            this.deliveryMethod = deliveryMethod;
            return this;
        }

        public Builder setId(String str) {
            this.id = str;
            return this;
        }

        public Builder setLanguageCode(String str) {
            this.languageCode = str;
            return this;
        }

        public Builder setManifestUrl(String str) {
            this.manifestUrl = str;
            return this;
        }

        public Builder setMediaFormat(MediaFormat mediaFormat) {
            this.mediaFormat = mediaFormat;
            return this;
        }
    }

    private SubtitlesStream(String str, String str2, boolean z, MediaFormat mediaFormat, DeliveryMethod deliveryMethod, String str3, boolean z2, String str4) {
        super(str, str2, z, mediaFormat, deliveryMethod, str4);
        this.locale = LocaleCompat.forLanguageTag(str3).orElseThrow(new d(str3, 5));
        this.code = str3;
        this.format = mediaFormat;
        this.autoGenerated = z2;
    }

    /* JADX INFO: Access modifiers changed from: private */
    public static /* synthetic */ ParsingException lambda$new$0(String str) {
        return new ParsingException(b.n("not a valid locale language code: ", str));
    }

    @Override // org.schabi.newpipe.extractor.stream.Stream
    public boolean equalStats(Stream stream) {
        if (!super.equalStats(stream) || !(stream instanceof SubtitlesStream)) {
            return false;
        }
        SubtitlesStream subtitlesStream = (SubtitlesStream) stream;
        return this.code.equals(subtitlesStream.code) && this.autoGenerated == subtitlesStream.autoGenerated;
    }

    public String getDisplayLanguageName() {
        Locale locale = this.locale;
        return locale.getDisplayName(locale);
    }

    public String getExtension() {
        return this.format.suffix;
    }

    @Override // org.schabi.newpipe.extractor.stream.Stream
    public ItagItem getItagItem() {
        return null;
    }

    public String getLanguageTag() {
        return this.code;
    }

    public Locale getLocale() {
        return this.locale;
    }

    public boolean isAutoGenerated() {
        return this.autoGenerated;
    }

    public /* synthetic */ SubtitlesStream(String str, String str2, boolean z, MediaFormat mediaFormat, DeliveryMethod deliveryMethod, String str3, boolean z2, String str4, int i) {
        this(str, str2, z, mediaFormat, deliveryMethod, str3, z2, str4);
    }
}
